---
abstract: 'fetch website thumbnails via webthumb.bluga.net'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Bluga-Webthumb
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5: 0
  LWP::Simple: 0
  Path::Class: 0
  Test::More: 0
  URI: 0
resources:
  bugtracker: https://github.com/bigpresh/WebService-Bluga-Webthumb/issues
  homepage: https://github.com/bigpresh/WebService-Bluga-Webthumb/
  repository: https://github.com/bigpresh/WebService-Bluga-Webthumb
version: 0.04
